version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/employee

  frontend:
    build: ./vite-project
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  mongo-data: